### ISSUE TITLE
Resources are not provisioned in OpenShift 4.3

### ISSUE THREAD

**Issue by displague** [crossplane/stack-aws-sample#17]
While testing https://github.com/operator-framework/community-operators/pull/1461 with @screeley44, we encountered problems provisioning `MinimalAWS` resources in an OpenShift 4.3 environment. 

This problem was resolved with a suggestion from @muvaf to manually include `minimalaws/finalizers` in the list of rules given to the `stack:$ns:minimal-aws:v0.3.0:system` clusterrole.

```yaml
apiVersion: aws.resourcepacks.crossplane.io/v1alpha1
kind: MinimalAWS
metadata:
  annotations:
  name: minimal-aws-provider
spec:
  credentialsSecretRef:
    key: credentials
    name: aws-account-creds
    namespace: aws-account-creds
  projectID: aws-test-project
  region: us-east-1
status:
  conditions:
  - lastTransitionTime: "2020-04-02T20:06:07Z"
    message: 'apply failed: minimal-aws-provider-replicationgroup/ of type cache.aws.crossplane.io/v1beta1,
      Kind=ReplicationGroupClass: could not create child resource: replicationgroupclasses.cache.aws.crossplane.io
      "minimal-aws-provider-replicationgroup" is forbidden: cannot set blockOwnerDeletion
      if an ownerReference refers to a resource you can''t set finalizers on: , <nil>'
    reason: Encountered an error during resource reconciliation
    status: "False"
    type: Synced
```
